bump golang 1.22.0 and update controller-runtime
kubernetes-sigs/network-policy-api pull request #238
Opened 2024-07-08 04:49 UTC by astoycos

2024-07-08 17:19 UTC, astoycos commented on hack/update-codegen.sh
> +# mkdir -p "$GOPATH/src/sigs.k8s.io"
Ah nit I can delete these comments

2024-07-08 17:19 UTC, astoycos commented on hack/update-codegen.sh
> +paths="${API_DIR}"
Nit newline

2024-07-09 16:38 UTC, tssurya requested changes

2024-07-09 16:38 UTC, tssurya commented on go.mod
> +toolchain go1.22.5
we shouldn't have this set

2024-07-09 17:42 UTC, astoycos commented on go.mod
> +toolchain go1.22.5
Done!

2024-07-09 19:01 UTC, Dyanngg approved these changes
LGTM overall

2024-07-09 19:01 UTC, Dyanngg commented on hack/update-codegen.sh
> +readonly API_VERSION=v1alpha1
I like that we now have a single place in the script for version. Let's maybe also add a reminder that everytime there's a spec bump this need to be updated

2024-07-21 06:44 UTC, tssurya approved these changes
/lgtm

2024-08-23 14:25 UTC, merged